name: Auto Data Agent (3‑hourly)

on:
  schedule:
    - cron: '0 */3 * * *'
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas requests beautifulsoup4 schedule

      - name: Run Auto Data Agent
        run: python auto_data_agent.py

      - name: Upload output artifacts
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: auto_data_agent_output
          path: |
            output/**
            logs/**
